[build]
  command = "pnpm run build"
  publish = "dist"

[dev]
  command = "pnpm run dev"
  port = 3000

[functions]
  directory = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  VITE_API_BASE_URL = "https://xpressdine-backend.vercel.app"
